# Mental Disorder Classification

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
mental_dis = pd.read_csv('/kaggle/input/mental-disorder-classification/Dataset-Mental-Disorders.csv')
mental_dis.head()

,Patient Number,Sadness,Euphoric,Exhausted,Sleep dissorder,Mood Swing,Suicidal thoughts,Anorxia,Authority Respect,Try-Explanation,Aggressive Response,Ignore & Move-On,Nervous Break-down,Admit Mistakes,Overthinking,Sexual Activity,Concentration,Optimisim,Expert Diagnose
0,Patiant-01,Usually,Seldom,Sometimes,Sometimes,YES,YES,NO,NO,YES,NO,NO,YES,YES,YES,3 From 10,3 From 10,4 From 10,Bipolar Type-2
1,Patiant-02,Usually,Seldom,Usually,Sometimes,NO,YES,NO,NO,NO,NO,NO,NO,NO,NO,4 From 10,2 From 10,5 From 10,Depression
2,Patiant-03,Sometimes,Most-Often,Sometimes,Sometimes,YES,NO,NO,NO,YES,YES,NO,YES,YES,NO,6 From 10,5 From 10,7 From 10,Bipolar Type-1
3,Patiant-04,Usually,Seldom,Usually,Most-Often,YES,YES,YES,NO,YES,NO,NO,NO,NO,NO,3 From 10,2 From 10,2 From 10,Bipolar Type-2
4,Patiant-05,Usually,Usually,Sometimes,Sometimes,NO,NO,NO,NO,NO,NO,NO,YES,YES,YES,5 From 10,5 From 10,6 From 10,Normal

In [3]:
mental_dis = mental_dis.drop('Patient Number', axis=1)

<a id="1" ></a>
## Map descriptive labels to numeric values

In [ ]:
missing_data = mental_dis.isnull().sum()
missing_data

In [5]:
yes_and_no_columns = ['Mood Swing', 'Suicidal thoughts', 'Anorxia', 'Authority Respect', 'Try-Explanation', 'Aggressive Response', 'Ignore & Move-On', 'Nervous Break-down', 'Admit Mistakes', 'Overthinking']

for column in yes_and_no_columns:
    mental_dis[column] = mental_dis[column].map({'YES': 1, 'NO': 0}).astype(int)
    
mental_dis.head()

,Sadness,Euphoric,Exhausted,Sleep dissorder,Mood Swing,Suicidal thoughts,Anorxia,Authority Respect,Try-Explanation,Aggressive Response,Ignore & Move-On,Nervous Break-down,Admit Mistakes,Overthinking,Sexual Activity,Concentration,Optimisim,Expert Diagnose
0,Usually,Seldom,Sometimes,Sometimes,1,1,0,0,1,0,0,1,1,1,3 From 10,3 From 10,4 From 10,Bipolar Type-2
1,Usually,Seldom,Usually,Sometimes,0,1,0,0,0,0,0,0,0,0,4 From 10,2 From 10,5 From 10,Depression
2,Sometimes,Most-Often,Sometimes,Sometimes,1,0,0,0,1,1,0,1,1,0,6 From 10,5 From 10,7 From 10,Bipolar Type-1
3,Usually,Seldom,Usually,Most-Often,1,1,1,0,1,0,0,0,0,0,3 From 10,2 From 10,2 From 10,Bipolar Type-2
4,Usually,Usually,Sometimes,Sometimes,0,0,0,0,0,0,0,1,1,1,5 From 10,5 From 10,6 From 10,Normal

In [ ]:
mental_dis['Sexual Activity'].dtype

In [6]:
mental_dis = mental_dis.rename(columns={'Optimisim': 'Optimism'})
mental_dis = mental_dis.rename(columns={'Anorxia': 'Anorexia'})

In [7]:
from_columns = ['Sexual Activity', 'Concentration', 'Optimism']
for column in from_columns:
    mental_dis[column] = mental_dis[column].astype(str).str.extract('(\d)')
    mental_dis[column] = pd.to_numeric(mental_dis[column])
    
mental_dis.head()

,Sadness,Euphoric,Exhausted,Sleep dissorder,Mood Swing,Suicidal thoughts,Anorexia,Authority Respect,Try-Explanation,Aggressive Response,Ignore & Move-On,Nervous Break-down,Admit Mistakes,Overthinking,Sexual Activity,Concentration,Optimism,Expert Diagnose
0,Usually,Seldom,Sometimes,Sometimes,1,1,0,0,1,0,0,1,1,1,3,3,4,Bipolar Type-2
1,Usually,Seldom,Usually,Sometimes,0,1,0,0,0,0,0,0,0,0,4,2,5,Depression
2,Sometimes,Most-Often,Sometimes,Sometimes,1,0,0,0,1,1,0,1,1,0,6,5,7,Bipolar Type-1
3,Usually,Seldom,Usually,Most-Often,1,1,1,0,1,0,0,0,0,0,3,2,2,Bipolar Type-2
4,Usually,Usually,Sometimes,Sometimes,0,0,0,0,0,0,0,1,1,1,5,5,6,Normal

In [8]:
frequency_columns = ['Sadness', 'Euphoric', 'Exhausted', 'Sleep dissorder']
for column in frequency_columns:
    mental_dis[column] = mental_dis[column].map({'Seldom': 0, 'Sometimes': 1, 'Usually': 2, 'Most-Often': 3}).astype(int)
    
mental_dis.head()

,Sadness,Euphoric,Exhausted,Sleep dissorder,Mood Swing,Suicidal thoughts,Anorexia,Authority Respect,Try-Explanation,Aggressive Response,Ignore & Move-On,Nervous Break-down,Admit Mistakes,Overthinking,Sexual Activity,Concentration,Optimism,Expert Diagnose
0,2,0,1,1,1,1,0,0,1,0,0,1,1,1,3,3,4,Bipolar Type-2
1,2,0,2,1,0,1,0,0,0,0,0,0,0,0,4,2,5,Depression
2,1,3,1,1,1,0,0,0,1,1,0,1,1,0,6,5,7,Bipolar Type-1
3,2,0,2,3,1,1,1,0,1,0,0,0,0,0,3,2,2,Bipolar Type-2
4,2,2,1,1,0,0,0,0,0,0,0,1,1,1,5,5,6,Normal

<a id="2" ></a>
## EDA

In [ ]:
mental_dis.describe()

<a id="3" ></a>
### Heatmap for correlation analysis

In [ ]:
import seaborn as sns 
import matplotlib.pyplot as plt

sns.set(style="whitegrid")

correlation_matrix = mental_dis.corr()

# create a heatmap
plt.figure(figsize=(14, 14))
heatmap = sns.heatmap(correlation_matrix, annot = True, fmt = ".2f", cmap = 'coolwarm')

plt.title('Correlation Heatmap')
plt.show()

<a id="4" ></a>
### Stacked bar plot for each level of sadness

Sadness levels:
- Seldom: 0
- Sometimes: 1
- Usually: 2
- Most-Often: 3

Expert Diagnose: 
- Normal: 0
- Bipolar Type-1: 1
- Bipolar Type-2: 2
- Depression: 3

In [ ]:
sns.countplot(x = 'Sadness', hue = 'Expert Diagnose', data = mental_dis, palette = 'viridis')
plt.title('Distribution of Sadness for Each Expert Diagnose Level')
plt.xlabel('Sadness')
plt.ylabel('Count')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))

sns.barplot(y = 'Optimism', x = 'Sexual Activity', hue = 'Expert Diagnose', data = mental_dis, errorbar = None, palette = 'viridis')
plt.title('Relationship between Optimism and Sexual Activity')
plt.xlabel('Sexual activity')
plt.ylabel('Optimism')

# place the legend at the top-right corner of the plot, outside the plot area
plt.legend(title = 'Expert Diagnose', bbox_to_anchor=(1, 1))

plt.show()

LOGISTIC REGRESSION WITH REGULARIZATION

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,ConfusionMatrixDisplay
from sklearn.model_selection import GridSearchCV

In [11]:
X = mental_dis.iloc[:, :-1]
y = mental_dis['Expert Diagnose']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1 ,random_state=101)
scaler = MinMaxScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [ ]:
#fit model with one-vs-rest classification
log_model = LogisticRegression(solver='saga',multi_class="ovr",max_iter=5000000)
#fit model with l1,l2,elasticnet
penalty = ['l1','l2','elasticnet']
#adding the lambda
C= np.logspace(1,10,50)
#adding the alpha for elastic-net
l1_ratio = np.linspace(0,1,50)
grid_model = GridSearchCV(log_model,param_grid={'C':C,'penalty':penalty,'l1_ratio'= l1_ratio})
grid_model.fit(scaled_X_train,y_train)
y_pred_test = grid_model.predict(X_test)
print('Classification report:')
print(classification_report(y_test, y_pred_test))

<a id="6" ></a>
## Random Forest

<a id="7" ></a>
### Grid search for hyperparameter tuning

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import GridSearchCV

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

# Create param_grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

rf_classifier = RandomForestClassifier(random_state = 0)

# Make GridSearchCV
grid_search = GridSearchCV(estimator = rf_classifier, param_grid = param_grid, verbose = 0)

# fit model
grid_search.fit(X_train, y_train)

# create best parameters
best_params = grid_search.best_params_
print("Best Parameters:", best_params)

Best Parameters: {'max_depth': None, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 100}

In [24]:
optimized_rf_classifier = RandomForestClassifier(**best_params, random_state = 0) # dict unpacking

# fit the new classifier on the training data
optimized_rf_classifier.fit(X_train, y_train)

# make predictions on the test and train data
y_pred_test1 = optimized_rf_classifier.predict(X_test)
print(classification_report(y_test, y_pred_test1))

                precision    recall  f1-score   support

Bipolar Type-1       1.00      1.00      1.00         2
Bipolar Type-2       1.00      1.00      1.00         3
    Depression       1.00      1.00      1.00         1
        Normal       1.00      1.00      1.00         6

      accuracy                           1.00        12
     macro avg       1.00      1.00      1.00        12
  weighted avg       1.00      1.00      1.00        12